[template]
src = "config.txt.tmpl"
dest = "/srv/xmr-stak/config.txt"
uid = 0
gid = 0
mode = "0644"
keys = [
  "/xmrstak",
]
#check_cmd = "/usr/sbin/nginx -t -c {{.src}}"
#reload_cmd = "/usr/sbin/service nginx restart"